<?php

/**
 * @file
 * Hooks for form alterations.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function o2e_obe_form_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $current_page = $form_state->get('current_page');
  $tempstore_service = \Drupal::service('tempstore.private')->get('o2e_obe_salesforce');
  // Populate Service ID in step 2.
  if ($current_page === 'step2') {
   $serviceId = \Drupal::service('tempstore.private')->get('o2e_obe_salesforce')->get('response');
   $form['elements']['step2']['service_id']['#default_value'] = $serviceId['service_id'];
   // Check for Show/Hide Slot Hold Time Message Configurations.
   $salesForceConfiguration = \Drupal::config('o2e_obe_salesforce.settings');
   $slotHoldTimeConfigStatus = $salesForceConfiguration->get('sf_available_time')['show_holdtime_message'];
   $slotHoldTimeTempStatus = $tempstore_service->get('slotHoldTime');
   if ($slotHoldTimeConfigStatus == TRUE && $slotHoldTimeTempStatus == TRUE) {
    // Get pick up date and arrival time.
    if (!empty($form_state->getValue('pick_up_date'))) {
      $pick_up_date = $form_state->getValue('pick_up_date');
      $arrival_time = $form_state->getValue('arrival_time');
    }
    // Get Slot Hold Time Message and Slot Hold Time Sub Message.
    if (!empty($salesForceConfiguration->get('sf_available_time.slot_holdtime_message'))) {
      $slot_holdtime_message = $salesForceConfiguration->get('sf_available_time.slot_holdtime_message');
      $slot_holdtime_sub_message = !empty($salesForceConfiguration->get('sf_available_time.slot_holdtime_sub_message'))
        ? $salesForceConfiguration->get('sf_available_time.slot_holdtime_sub_message')
        : '';
      // Design the message.
      $hold_time_message = '<div class="holdtime-section"><div class="holdtime-main">' . $slot_holdtime_message . '<span class="hold-slot">' . $pick_up_date . ' ' . $arrival_time . '</span></div><div class="holdtime-subtext">' . $slot_holdtime_sub_message . '</div></div>';
      $form['elements']['step2']['holdtime_data']['#access'] = TRUE;
      $form['elements']['step2']['holdtime_data']['#template'] = $hold_time_message;
    }
   }
  }
  // Add Custom Edit buttton to step 2 from step 3.
  if ($current_page === 'step3') {
    $form['calendar'] = [
      "#type" => "submit",
      "#value" => "Edit Slots",
      "#webform_actions_button_custom" => FALSE,
      "#submit" => ['_o2e_obe_form_calendar_redirect'],
      "#weight" => 0,
      "#attributes" => [
        "formnovalidate" => "formnovalidate",
      ],
      "#validate" => ['::noValidate'],
    ];
    // Get Data related to postal code from tempstore.
    $postal_code_data = $tempstore_service->get('postalCodeData');
    // Auto Populate state code and postal code in Address field.
    $form['elements']['step3']['address']['#default_value']['postal_code'] = $postal_code_data['zip_code'];
    $form['elements']['step3']['address']['#default_value']['state_province'] = $postal_code_data['state'];
    // Set the country name based on postal code.
    $country = '';
    $zip_code = $postal_code_data['zip_code'];
    if (preg_match('#[0-9]{5}#', $zip_code)) {
      $country = 'United States';
      $tempstore_service->set('country_code', 'US');
    }
    elseif (preg_match('/^([a-zA-Z]\d[a-zA-Z])\ {0,1}(\d[a-zA-Z]\d)$/', $zip_code)) {
      $country = 'Canada';
      $tempstore_service->set('country_code', 'CA');
    }
    elseif (preg_match('#[0-9]{4}#', $zip_code)) {
      $country = 'Australia';
      $tempstore_service->set('country_code', 'AU');
    }
    $form['elements']['step3']['address']['#default_value']['country'] = $country;
  }
  // Add custom button to step 2 and step 3 from step 4.
  if ($current_page === 'step4') {
    $form['calendar'] = [
      "#type" => "submit",
      "#value" => "Edit Slots",
      "#webform_actions_button_custom" => FALSE,
      "#submit" => ['_o2e_obe_form_calendar_redirect'],
      "#weight" => 0,
      "#attributes" => [
        "formnovalidate" => "formnovalidate",
      ],
      "#validate" => ['::noValidate'],
    ];
    $form['contact'] = [
      "#type" => "submit",
      "#value" => "Edit Contact Information",
      "#webform_actions_button_custom" => FALSE,
      "#submit" => ['_o2e_obe_form_contact_redirect'],
      "#weight" => 0,
      "#attributes" => [
        "formnovalidate" => "formnovalidate",
      ],
      "#validate" => ['::noValidate'],
    ];
  }
  if (isset($form['#webform_id']) && $form['#webform_id'] === 'o2e_webform') {
    $form['elements']['step3']['address']['#after_build'][] = '_update_address';
  }
}

/**
 * Custom function to hide country field.
 */
function _update_address($element, FormStateInterface $form_state) {
  $element['country']['#attributes']['hidden'] = TRUE;
  return $element;
}

/**
 * Custom Redirection of form after 15 mins expiry.
 */
function goto_step($page, $pages, FormStateInterface $form_state) {
  // Convert associative array to index for easier manipulation.
  $all_keys = array_keys($pages);
  $goto_destination_page_index = array_search($page, $all_keys);
  if ($goto_destination_page_index > 0) {
    // The backend pointer for page will add 1 so to go our page we must -1.
    $form_state->set('current_page', $all_keys[$goto_destination_page_index - 1]);
    $form_state->setRebuild();
  }
}

/**
 * Function to check expiry of 900 seconds.
 */
function check_local_time_expiry($currentTime) {
  $currentLocalTimeTemp = \Drupal::service('tempstore.private')->get('o2e_obe_salesforce')->get('currentLocalTime');
  $service_expiry = \Drupal::config('o2e_obe_salesforce.settings')->get('sf_verify_area')['service_expiry'];
  if ($currentLocalTimeTemp['currentTimeStamp']) {
    $timeDifference = $currentTime - $currentLocalTimeTemp['currentTimeStamp'];
    if (abs($timeDifference) < $service_expiry) {
      return TRUE;
    }
    else {
      return FALSE;
    }
  }
  else {
    return FALSE;
  }
}

/**
 * Custom function to redirect to step 2 for data Update.
 */
function _o2e_obe_form_calendar_redirect(&$form, FormStateInterface $form_state) {
  $pages = $form_state->get('pages');
  goto_step_redirect('step2', $pages, $form_state);
}

/**
 * Custom function to redirect to step 3 for data Update.
 */
function _o2e_obe_form_contact_redirect(&$form, FormStateInterface $form_state) {
  $pages = $form_state->get('pages');
  goto_step_redirect('step3', $pages, $form_state);
}

/**
 * Custom function to redirect to page2 on click of custom edit button of form.
 */
function goto_step_redirect($page, $pages, FormStateInterface $form_state) {
  // Convert associative array to index for easier manipulation.
  $all_keys = array_keys($pages);
  $goto_destination_page_index = array_search($page, $all_keys);
  if ($goto_destination_page_index > 0) {
    $form_state->set('current_page', $all_keys[$goto_destination_page_index]);
    $form_state->setRebuild();
  }
}
