<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 *
 */
function o2e_obe_form_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $current_page = $form_state->get('current_page');
  if ($current_page === 'step3') {
    $form['actions']['calendar'] = [
      "#type" => "submit",
      "#value" => "Edit Slots",
      "#webform_actions_button_custom" => false,
      "#submit" => ['_o2e_obe_form_calendar_redirect'],
      "#weight" => 0,
      "#attributes" => [
        "formnovalidate" =>"formnovalidate",
      ],
      "#validate" => ['::noValidate'],
    ];
  }
  if ($current_page === 'step4') {
    $form['actions']['calendar'] = [
      "#type" => "submit",
      "#value" => "Edit Slots",
      "#webform_actions_button_custom" => false,
      "#submit" => ['_o2e_obe_form_calendar_redirect'],
      "#weight" => 0,
      "#attributes" => [
        "formnovalidate" =>"formnovalidate",
      ],
      "#validate" => ['::noValidate'],
    ];
    $form['actions']['contact'] = [
      "#type" => "submit",
      "#value" => "Edit Contact Information",
      "#webform_actions_button_custom" => false,
      "#submit" => ['_o2e_obe_form_contact_redirect'],
      "#weight" => 0,
      "#attributes" => [
        "formnovalidate" =>"formnovalidate",
      ],
      "#validate" => ['::noValidate'],
    ];
  }
  if (isset($form['#webform_id']) && $form['#webform_id'] === 'o2e_webform') {
    $form['elements']['step3']['address']['#after_build'][] = '_update_address';
  }
}

function _update_address($element, FormStateInterface $form_state) {
  $element['country']['#attributes']['hidden'] = TRUE;
  return $element;
}

/** 
 * Custom Redirection of form after 15 mins expiry.
 */
function goto_step($page, $pages, FormStateInterface $form_state) {
  // Convert associative array to index for easier manipulation.
  $all_keys = array_keys($pages);
  $goto_destination_page_index = array_search($page, $all_keys);
  if ($goto_destination_page_index > 0){
    // The backend pointer for page will add 1 so to go our page we must -1.
    $form_state->set('current_page', $all_keys[$goto_destination_page_index-1]);
  }

}

/**
 * Function to check expiry of 900seconds.
 *
 * @param string $currentTime
 * @return bool
 */
function checkLocalTimeExpiry($currentTime) {
  $tempstore = \Drupal::service('tempstore.private')->get('o2e_obe_salesforce')->get('currentLocalTime');
  if ($tempstore['currentTimeStamp']) {
    $timeDifference = $currentTime - $tempstore['currentTimeStamp'];
    if (abs($timeDifference) < 900) {
      return TRUE;
    }
    else {
      return FALSE;
    }
  }
  else {
    return FALSE;
  }
}

/**
 * Custom function to redirect to step 2 for data Update
 */
function _o2e_obe_form_calendar_redirect(&$form, FormStateInterface $form_state) {
  $pages = $form_state->get('pages');
  goto_step('step2', $pages, $form_state);
}

/**
 * Custom function to redirect to step 3 for data Update
 */
function _o2e_obe_form_contact_redirect(&$form, FormStateInterface $form_state) {
  $pages = $form_state->get('pages');
  goto_step('step3', $pages, $form_state);
}
