<?php

/**
 * @file
 * Hooks for form alterations.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function o2e_obe_form_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['#webform_id']) && $form['#webform_id'] === 'o2e_webform') {
    $tempstore_service = \Drupal::service('tempstore.private')->get('o2e_obe_salesforce');
    $current_page = $form_state->get('current_page');
    $page_array = !empty($form_state->get('pages')) ? array_keys($form_state->get('pages')) : [];
    foreach ($page_array as $page) {
      if ($current_page === $page) {
        if (isset($form['elements'][$current_page]['service_id'])) {
          // Populate Service ID.
          $serviceId = $tempstore_service->get('response');
          $form['elements'][$current_page]['service_id']['#default_value'] = $serviceId['service_id'];
        }
        if (isset($form['elements'][$current_page]['address'])) {
          $form['elements'][$current_page]['address']['#after_build'][] = '_update_address';
          // Get Data related to postal code from tempstore.
          $postal_code_data = $tempstore_service->get('postalCodeData');
          // Auto Populate state code and postal code in Address field.
          $form['elements'][$current_page]['address']['#default_value']['postal_code'] = $postal_code_data['zip_code'];
          if (!empty($postal_code_data['state']) && empty($form['elements'][$current_page]['address']['#default_value']['state_province'])) {
            $form['elements'][$current_page]['address']['#default_value']['state_province'] = $postal_code_data['state'];
          }
          // Set the country name based on postal code.
          $country = '';
          $zip_code = $postal_code_data['zip_code'];
          if (preg_match('#[0-9]{5}#', $zip_code)) {
            $country = 'United States';
            $tempstore_service->set('country_code', 'US');
          }
          elseif (preg_match('/^([a-zA-Z]\d[a-zA-Z])\ {0,1}(\d[a-zA-Z]\d)$/', $zip_code)) {
            $country = 'Canada';
            $tempstore_service->set('country_code', 'CA');
          }
          elseif (preg_match('#[0-9]{4}#', $zip_code)) {
            $country = 'Australia';
            $tempstore_service->set('country_code', 'AU');
          }
          $form['elements'][$current_page]['address']['#default_value']['country'] = $country;
        }
      }
    }

    // Brand name attached to drupalSettings.
    $brand_name = \Drupal::config('o2e_obe_common.settings')->get('o2e_obe_common.brand');
    $form['#attached']['drupalSettings']['brand_name'] = (!empty($brand_name)) ? $brand_name : 'default';
  }
}

/**
 * Custom function to hide country field.
 */
function _update_address($element, FormStateInterface $form_state) {
  $element['country']['#attributes']['hidden'] = TRUE;
  return $element;
}

/**
 * Custom Redirection of form after 15 mins expiry.
 */
function goto_step($page, $pages, FormStateInterface $form_state) {
  // Convert associative array to index for easier manipulation.
  $all_keys = array_keys($pages);
  $goto_destination_page_index = array_search($page, $all_keys);
  if ($goto_destination_page_index > 0) {
    // The backend pointer for page will add 1 so to go our page we must -1.
    $submission = $form_state->getFormObject()->getEntity();
    $submission->setCurrentPage($all_keys[$goto_destination_page_index])->save();
    $form_state->set('current_page', $all_keys[$goto_destination_page_index]);
    $form_state->setRebuild();
  }
}

/**
 * Function to check expiry of 900 seconds.
 */
function check_local_time_expiry() {
  $currentTime = \Drupal::service('datetime.time')->getRequestTime();
  $currentLocalTimeTemp = \Drupal::service('tempstore.private')->get('o2e_obe_salesforce')->get('currentLocalTime');
  $service_expiry = \Drupal::config('o2e_obe_salesforce.settings')->get('sf_verify_area')['service_expiry'];
  $service_expiry = (int)($service_expiry);
  if (!empty($currentLocalTimeTemp) && $currentLocalTimeTemp['currentTimeStamp']) {
    $timeDifference = $currentTime - $currentLocalTimeTemp['currentTimeStamp'];
    if (abs($timeDifference) < $service_expiry) {
      return TRUE;
    }
    else {
      return FALSE;
    }
  }
  else {
    return FALSE;
  }
}
