# Schema for the configuration files of the salesforce module.

o2e_obe_salesforce.settings:
  type: config_object
  label: 'Salesforce Settings'
  mapping:
    api:
      type: mapping
      label: 'Fieldset for the fields'
      mapping:
        login_url:
          type: text
          label: 'Login URL'
        api_username:
          type: text
          label: 'API username'
        api_password:
          type: text
          label: 'API password'
        grant_type:
          type: text
          label: 'OBE Grant Type'
        client_id:
          type: text
          label: 'OBE Client ID'
        client_secret:
          type: text
          label: 'OBE Client Secret'
        duration:
          type: text
          label: 'Expire Druration'
        brand:
          type: text
          label: 'Brand'
        api_url_segment:
          type: text
          label: 'Api URL Segment'
